### ISSUE TITLE
npm install is throwing error 

### ISSUE THREAD

**Issue by yogeshbalan** [TelescopeJS/nova-docs#4]
npm http GET https://registry.npmjs.org/hexo-deployer-git
npm http GET https://registry.npmjs.org/handlebars
npm http GET https://registry.npmjs.org/hexo/3.2.0
npm http GET https://registry.npmjs.org/hexo-generator-archive
npm http GET https://registry.npmjs.org/hexo-generator-category
npm http GET https://registry.npmjs.org/hexo-generator-cname
npm http GET https://registry.npmjs.org/hexo-generator-index
npm http GET https://registry.npmjs.org/hexo-generator-tag
npm http GET https://registry.npmjs.org/hexo-renderer-ejs
npm http GET https://registry.npmjs.org/hexo-renderer-less
npm http GET https://registry.npmjs.org/hexo-renderer-marked
npm http GET https://registry.npmjs.org/hexo-server
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/showdown
npm http GET https://registry.npmjs.org/hexo-s3-deploy
npm http 304 https://registry.npmjs.org/hexo-generator-category
npm http 304 https://registry.npmjs.org/hexo-generator-archive
npm ERR! Error: EACCES, mkdir '/home/yogesh/tmp/npm-27070-_Mt8o7ha'
npm ERR!  { [Error: EACCES, mkdir '/home/yogesh/tmp/npm-27070-_Mt8o7ha']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/yogesh/tmp/npm-27070-_Mt8o7ha' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.13.0-105-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/yogesh/WebDev/nova-docs
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/yogesh/tmp/npm-27070-_Mt8o7ha
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/yogesh/tmp/npm-27070-_Mt8o7ha'
npm http 304 https://registry.npmjs.org/handlebars
npm http 304 https://registry.npmjs.org/hexo-deployer-git
npm http 304 https://registry.npmjs.org/hexo/3.2.0
npm http 304 https://registry.npmjs.org/hexo-generator-cname
npm http 304 https://registry.npmjs.org/hexo-generator-index
npm http 304 https://registry.npmjs.org/hexo-generator-tag
npm http 304 https://registry.npmjs.org/hexo-renderer-ejs
npm http 304 https://registry.npmjs.org/hexo-renderer-less
npm http 304 https://registry.npmjs.org/hexo-renderer-marked
npm http 304 https://registry.npmjs.org/hexo-server
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/showdown
npm http 304 https://registry.npmjs.org/hexo-s3-deploy
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/yogesh/WebDev/nova-docs/npm-debug.log
npm ERR! not ok code 0

**Comment by xavcz** [comment]
```
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
```
You need to have at least NPM v3, and I would recommend using Node v6.x. NVM is a great way to manage your Node versions: http://nvm.sh

```
npm ERR! Please try running this command again as root/Administrator.
```
Follow this recommendation too, it may help :)

Btw, what is `hexo`? We do not depend on it.
